name:                Skater
version:             0.0.0.1
github:              "fusiled/Skater"
license:             BSD3
author:              "fusiled"
maintainer:          "fusiled@gmail.com"
copyright:           "2018 Matteo Maria Fusi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fusiled/Skater#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- exceptions
- turtle
- criterion
- bytestring
- aeson
- text


library:
  source-dirs: src

executables:
  Skater-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Skater

tests:
  Skater-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Skater
